### PR TITLE
Make the standard theme more like a regular theme

### PR DESCRIPTION
**Pull request by ortiza5**
Based off of the suggestion here: https://forum.vivaldi.net/post/596459

Just made the standard theme a bit more like a regular theme. The only difference from the other themes is that I disabled the removal and editing buttons.

### CODE REVIEW

**Comment by luetage** [comment]
As far as I can see you load custom.css for the standard theme now and run all the color changes. The point of the standard theme is that there aren’t any theming changes and you can use the forum mod without the theme machine rolling in and overtaking. It’s meant to be an option to stay with the forum theme and only take advantage of the modifications page. And it also loads its own barebones css file, which users could use to load their own full custom theme. Maybe I don’t get it though.

**Comment by ortiza5** [comment]
I was just about to add another commit that removes the `standard.css`.

Basically, the user wanted the `Add Theme` button to work while you have the standard theme selected. It felt easiest to just convert the standard theme to be like the other themes. Sure it adds some unnecessary CSS since the colors are the same as default, but it doesn't really hurt.

**Comment by ortiza5** [comment]
## New
image

## Old
image

**Comment by luetage** [comment]
I think we aren’t on the same page here. Please understand that calculating theme colors for the standard theme changes everything. You aren’t using Vivaldi’s own theming any more, but the theme machine, which is very intrusive. I want people to have the option to circumvent the theme machine and that’s why there is the standard theme, which loads its own stylesheet.

**Comment by luetage** [comment]
All the user really needs is someone recreating the standard theme in the theme-machine and then sharing the theme on the forum. Then they only have to click on it and it will load for them and then they can mess with it all they want in the theme machine.

**Comment by ortiza5** [comment]
Yeah, that makes sense.

The way I was viewing it, setting the colors of the standard theme inside of a custom theme would lead to pretty minimal deviations from the default color scheme of the forum. But I am sure there are some differences as a result of the changes.

I tried just enabling the `Add Theme` button for the standard theme, but since it isn't like the other custom themes, it didn't work properly.

> All the user really needs is someone recreating the standard theme in the theme-machine and then sharing the theme on the forum. Then they only have to click on it and it will load for them and then they can mess with it all they want in the theme machine.

True, but it seems reasonable that the button should work. There are other ways to go about it than the way I wrote up of course, so I will leave it up to you.

It was only a quick attempt adding the functionality, so a better version that preserves the `standard.css` usage but still allows duplicating the theme can be done if you wish.

**Comment by luetage** [comment]
Yeah, activating the + button alone would make sense. Then instead of cloning the theme, like the + button would normally act, it loads the colors from the standard theme.

And yes, the changes the theme machine introduces are massive. It’s a 1400 lines CSS file after all… With the Standard theme it’s 63 lines…

**Comment by luetage** [comment]
Somehow the import of themes from the forum is broken… Not sure what is going on there, but I gotta leave now.

**Comment by ortiza5** [comment]
It is getting late here, so I won't work on it tonight. If you want to make the changes, go ahead.

I will go ahead and close this pull request since it won't use any of the same changes. Better to start with a fresh branch.

**Comment by luetage** [comment]
You would just need to enable the + button for the standard theme and then write an exception for the add theme function in theme-machine.js, which instead of loading the color variables from the current theme, loads fixed color hex codes.

**Pull request closed without merging**
