### PR TITLE
4.2

### PR DESCRIPTION
**Pull request by luetage**
Numerous changes and fixes for 4.2

### CODE REVIEW

**Comment by ortiza5** [comment]
Looks pretty good. I noticed 2 slight defects in the mobile view.

In the chats dropdown from the profile button, the text could probably be adjusted a bit.

image

And the hamburger menu seems oddly placed. Not sure what exact `left: ` value should be used. Maybe around `80px`?

image
 
---

Other than that it looks all good. I don't have any notifications to test, but it seems like you already did that.

It doesn't need to be for this release, but it probably would be good to make the mobile view menus follow the theme colors. I am sure most people never see them (I only noticed they weren't themed while testing), but would be good for consistency.

**Comment by luetage** [comment]
Yes, I don’t do much with mobile view. It isn’t worth it imo and would be a shitload of work to maintain and to style everything properly. The bug from your first picture exists in regular Vivaldi. Please report it to the tracker (community-web). I stopped fixing bugs that are not that obvious and which are present on regular forum. The second picture is a Vivaldi forum mod problem. Since I hide the picture (which includes both the logo and the text) the menu button is misplaced. It could only be fixed by making two adjustments, one for medium width and one for small width. Again, not worth it imo. It’s gonna break again anyway…

You should be able to see all past notifications by opening the notification dropdown. You only need to enable custom notification icons in modifications for the icons.

**Comment by luetage** [comment]
The only problem I noticed is the loading notification when first opening the notification dropdown after a reload. It goes 20px to the left. The only way to fix this (that I found) would be the `:has` selector. It’s currently on the dev branch on Chromium. Will hopefully be released soon.

**Comment by ortiza5** [comment]
Yeah, does it only do that when there is an unread notification?

**Comment by luetage** [comment]
No, it always does that, but only the first time the dropdown is opened after a reload. Maybe your internet connection is too good. You can load the forum, then turn off your internet connection and then click the notification dropdown, which will show the problem continuously.

**Pull request merged**
